main = "./src/index.ts"
compatibility_date = "2022-05-03"

[env.dev]
name = "rpc-proxy-dev"
vars = { ENVIRONMENT = 'dev'}

[env.production]
name="rpc-proxy"
vars = { ENVIRONMENT = 'production'}
zone_id = "a2734f38c3626f4cd99650383cec527a"
route = "rpc-proxy.solanaforgelabs.com"
