name: Build

on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      # Publish the "dev" (non-prod) environment
      - name: Publish Non-Prod (Dev)
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: dev
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      # Publish the "production" environment
      - name: Publish Prod
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
